//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod author;
pub mod book;
pub mod book_author;
pub mod book_genre;
pub mod book_rate;
pub mod chapter;
pub mod comment;
pub mod comment_rate;
pub mod genre;
pub mod user;
