//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::author::Entity as Author;
pub use super::book::Entity as Book;
pub use super::book_author::Entity as BookAuthor;
pub use super::book_genre::Entity as BookGenre;
pub use super::book_rate::Entity as BookRate;
pub use super::chapter::Entity as Chapter;
pub use super::comment::Entity as Comment;
pub use super::comment_rate::Entity as CommentRate;
pub use super::genre::Entity as Genre;
pub use super::user::Entity as User;
